name: credentialScan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  check-for-credentials:
    runs-on: ubuntu-latest
    container: trufflesecurity/trufflehog:latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PR - Scan for verified credentials
        if: github.event_name == 'pull_request'
        run:
          trufflehog git file://./ --only-verified --branch ${{ github.event.pull_request.head.ref }} --since-commit ${{ github.event.repository.default_branch }} --no-update --fail > /dev/null

      - name: PR - Scan for unverified credentials
        if: github.event_name == 'pull_request'
        run:
          trufflehog git file://./ --branch ${{ github.event.pull_request.head.ref }} --no-update > /dev/null

      - name: Push - Scan for verified credentials
        if: github.event_name == 'push' && github.event.ref_type == 'branch'
        run:
          trufflehog git file://./ --only-verified --since-commit ${{ github.event.repository.default_branch }} --branch HEAD --no-update --fail > /dev/null

      - name: Push - Scan for unverified credentials
        if: github.event_name == 'push' && github.event.ref_type == 'branch'
        run:
          trufflehog git file://./ --since-commit ${{ github.event.repository.default_branch }} --branch HEAD --no-update > /dev/null
